package com.gint.app.bisis4.client.circ.model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

/**
 * Bibliotekari generated by hbm2java
 */
public class Bibliotekari implements java.io.Serializable {

  // Fields   
	
	
  private String username;
	  
  private String password;
	
  private String ime;
  
  private String prezime;

  private String email;
  
  private String napomena;

  private int obrada;

  private int cirkulacija;

  private int administracija;

  private String context;

  // Constructors

  /** default constructor */
  public Bibliotekari() {
  }

  /** full constructor */
  public Bibliotekari(String username, String password, String ime, String prezime, String email, String napomena, int obrada, int cirkulacija,
      int administracija, String context) {
	this.username = username;
	this.password = password;
    this.ime = ime;
    this.prezime = prezime;
    this.email = email;
    this.napomena = napomena;
    this.obrada = obrada;
    this.cirkulacija = cirkulacija;
    this.administracija = administracija;
    this.context = context;
  }

  // Property accessors
  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }
  
  public String getPassword() {
	    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }
  
  public String getIme() {
    return this.ime;
  }

  public void setIme(String ime) {
    this.ime = ime;
  }

  public String getPrezime() {
    return this.prezime;
  }

  public void setPrezime(String prezime) {
    this.prezime = prezime;
  }
  
  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getNapomena() {
    return this.napomena;
  }

  public void setNapomena(String napomena) {
    this.napomena = napomena;
  }

  public int getObrada() {
    return this.obrada;
  }

  public void setObrada(int obrada) {
    this.obrada = obrada;
  }

  public int getCirkulacija() {
    return this.cirkulacija;
  }

  public void setCirkulacija(int cirkulacija) {
    this.cirkulacija = cirkulacija;
  }

  public int getAdministracija() {
    return this.administracija;
  }

  public void setAdministracija(int administracija) {
    this.administracija = administracija;
  }

  public String getContext() {
    return this.context;
  }

  public void setContext(String context) {
    this.context = context;
  }

}
