package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8


/**
 * WarningTypes generated by hbm2java
 */
public class Configs implements java.io.Serializable {

	// Fields    

	private String name;

	private String text;

	// Constructors

	/** default constructor */
	public Configs() {
	}

	/** minimal constructor */
	public Configs(String name) {
		this.name = name;
	}

	/** full constructor */
	public Configs(String name, String text) {
		this.name = name;
		this.text = text;
	}

	// Property accessors
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}
}
