package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Duplicate generated by hbm2java
 */
public class Duplicate implements java.io.Serializable {

	// Fields    

	private int id;

	private Users users;

	private int dupNo;

	private Date dupDate;

	// Constructors

	/** default constructor */
	public Duplicate() {
	}

	/** minimal constructor */
	public Duplicate(int id, Users users, int dupNo) {
		this.id = id;
		this.users = users;
		this.dupNo = dupNo;
	}

	/** full constructor */
	public Duplicate(int id, Users users, int dupNo, Date dupDate) {
		this.id = id;
		this.users = users;
		this.dupNo = dupNo;
		this.dupDate = dupDate;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getDupNo() {
		return this.dupNo;
	}

	public void setDupNo(int dupNo) {
		this.dupNo = dupNo;
	}

	public Date getDupDate() {
		return this.dupDate;
	}

	public void setDupDate(Date dupDate) {
		this.dupDate = dupDate;
	}

}
