package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * EduLvl generated by hbm2java
 */
public class EduLvl implements java.io.Serializable {

	// Fields    

	private int id;

	private String name;

	private Set userses = new HashSet(0);

	// Constructors

	/** default constructor */
	public EduLvl() {
	}

	/** minimal constructor */
	public EduLvl(int id) {
		this.id = id;
	}

	/** full constructor */
	public EduLvl(int id, String name, Set userses) {
		this.id = id;
		this.name = name;
		this.userses = userses;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
