package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Groups generated by hbm2java
 */
public class Groups implements java.io.Serializable {

	// Fields    

	private int sysId;

	private String userId;

	private String instName;

	private Date signDate;

	private String address;

	private String city;

	private Integer zip;

	private String phone;

	private String email;

	private String fax;

	private String secAddress;

	private String secCity;

	private Integer secZip;

	private String secPhone;

	private String contFname;

	private String contLname;

	private String contEmail;

	private Set userses = new HashSet(0);

	// Constructors

	/** default constructor */
	public Groups() {
	}

	/** minimal constructor */
	public Groups(int sysId, String userId) {
		this.sysId = sysId;
		this.userId = userId;
	}

	/** full constructor */
	public Groups(int sysId, String userId, String instName, Date signDate,
			String address, String city, Integer zip, String phone,
			String email, String fax, String secAddress, String secCity,
			Integer secZip, String secPhone, String contFname,
			String contLname, String contEmail, Set userses) {
		this.sysId = sysId;
		this.userId = userId;
		this.instName = instName;
		this.signDate = signDate;
		this.address = address;
		this.city = city;
		this.zip = zip;
		this.phone = phone;
		this.email = email;
		this.fax = fax;
		this.secAddress = secAddress;
		this.secCity = secCity;
		this.secZip = secZip;
		this.secPhone = secPhone;
		this.contFname = contFname;
		this.contLname = contLname;
		this.contEmail = contEmail;
		this.userses = userses;
	}

	// Property accessors
	public int getSysId() {
		return this.sysId;
	}

	public void setSysId(int sysId) {
		this.sysId = sysId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getInstName() {
		return this.instName;
	}

	public void setInstName(String instName) {
		this.instName = instName;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getSecAddress() {
		return this.secAddress;
	}

	public void setSecAddress(String secAddress) {
		this.secAddress = secAddress;
	}

	public String getSecCity() {
		return this.secCity;
	}

	public void setSecCity(String secCity) {
		this.secCity = secCity;
	}

	public Integer getSecZip() {
		return this.secZip;
	}

	public void setSecZip(Integer secZip) {
		this.secZip = secZip;
	}

	public String getSecPhone() {
		return this.secPhone;
	}

	public void setSecPhone(String secPhone) {
		this.secPhone = secPhone;
	}

	public String getContFname() {
		return this.contFname;
	}

	public void setContFname(String contFname) {
		this.contFname = contFname;
	}

	public String getContLname() {
		return this.contLname;
	}

	public void setContLname(String contLname) {
		this.contLname = contLname;
	}

	public String getContEmail() {
		return this.contEmail;
	}

	public void setContEmail(String contEmail) {
		this.contEmail = contEmail;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
