package com.gint.app.bisis4.client.circ.model;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8



/**
 * InternaOznaka generated by hbm2java
 */
public class InternaOznaka implements java.io.Serializable {

  // Fields    

  private String intOznId;

  private String intOznOpis;

  private Set godines = new HashSet(0);

  private Set primercis = new HashSet(0);

  // Constructors

  /** default constructor */
  public InternaOznaka() {
  }

  /** minimal constructor */
  public InternaOznaka(String intOznId, String intOznOpis) {
    this.intOznId = intOznId;
    this.intOznOpis = intOznOpis;
  }

  /** full constructor */
  public InternaOznaka(String intOznId, String intOznOpis, Set godines,
      Set primercis) {
    this.intOznId = intOznId;
    this.intOznOpis = intOznOpis;
    this.godines = godines;
    this.primercis = primercis;
  }

  // Property accessors
  public String getIntOznId() {
    return this.intOznId;
  }

  public void setIntOznId(String intOznId) {
    this.intOznId = intOznId;
  }

  public String getIntOznOpis() {
    return this.intOznOpis;
  }

  public void setIntOznOpis(String intOznOpis) {
    this.intOznOpis = intOznOpis;
  }

  public Set getGodines() {
    return this.godines;
  }

  public void setGodines(Set godines) {
    this.godines = godines;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

}
