package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	// Fields    

	private int id;

	private String name;

	private Integer lastUserId;

	private Set lendings = new HashSet(0);

	private Set signings = new HashSet(0);

	// Constructors

	/** default constructor */
	public Location() {
	}

	/** minimal constructor */
	public Location(int id) {
		this.id = id;
	}

	/** full constructor */
	public Location(int id, String name, Integer lastUserId, Set lendings,
			Set signings) {
		this.id = id;
		this.name = name;
		this.lastUserId = lastUserId;
		this.lendings = lendings;
		this.signings = signings;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getLastUserId() {
		return this.lastUserId;
	}

	public void setLastUserId(Integer lastUserId) {
		this.lastUserId = lastUserId;
	}

	public Set getLendings() {
		return this.lendings;
	}

	public void setLendings(Set lendings) {
		this.lendings = lendings;
	}

	public Set getSignings() {
		return this.signings;
	}

	public void setSignings(Set signings) {
		this.signings = signings;
	}

}
