package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

/**
 * Membership generated by hbm2java
 */
public class Membership implements java.io.Serializable {

	// Fields    

	private int id;

	private MmbrTypes mmbrTypes;

	private UserCategs userCategs;

	private Double cost;

	// Constructors

	/** default constructor */
	public Membership() {
	}

	/** minimal constructor */
	public Membership(int id, MmbrTypes mmbrTypes, UserCategs userCategs) {
		this.id = id;
		this.mmbrTypes = mmbrTypes;
		this.userCategs = userCategs;
	}

	/** full constructor */
	public Membership(int id, MmbrTypes mmbrTypes, UserCategs userCategs,
			Double cost) {
		this.id = id;
		this.mmbrTypes = mmbrTypes;
		this.userCategs = userCategs;
		this.cost = cost;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public MmbrTypes getMmbrTypes() {
		return this.mmbrTypes;
	}

	public void setMmbrTypes(MmbrTypes mmbrTypes) {
		this.mmbrTypes = mmbrTypes;
	}

	public UserCategs getUserCategs() {
		return this.userCategs;
	}

	public void setUserCategs(UserCategs userCategs) {
		this.userCategs = userCategs;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

}
