package com.gint.app.bisis4.client.circ.model;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8


/**
 * Odeljenje generated by hbm2java
 */
public class Odeljenje implements java.io.Serializable {

  // Fields    

  private String odeljenjeId;

  private String odeljenjeNaziv;

  private Set primercis = new HashSet(0);

  private Set godines = new HashSet(0);

  // Constructors

  /** default constructor */
  public Odeljenje() {
  }

  /** minimal constructor */
  public Odeljenje(String odeljenjeId, String odeljenjeNaziv) {
    this.odeljenjeId = odeljenjeId;
    this.odeljenjeNaziv = odeljenjeNaziv;
  }

  /** full constructor */
  public Odeljenje(String odeljenjeId, String odeljenjeNaziv, Set primercis,
      Set godines) {
    this.odeljenjeId = odeljenjeId;
    this.odeljenjeNaziv = odeljenjeNaziv;
    this.primercis = primercis;
    this.godines = godines;
  }

  // Property accessors
  public String getOdeljenjeId() {
    return this.odeljenjeId;
  }

  public void setOdeljenjeId(String odeljenjeId) {
    this.odeljenjeId = odeljenjeId;
  }

  public String getOdeljenjeNaziv() {
    return this.odeljenjeNaziv;
  }

  public void setOdeljenjeNaziv(String odeljenjeNaziv) {
    this.odeljenjeNaziv = odeljenjeNaziv;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

  public Set getGodines() {
    return this.godines;
  }

  public void setGodines(Set godines) {
    this.godines = godines;
  }

}
