package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Duplicate generated by hbm2java
 */
public class Picturebooks implements java.io.Serializable {

	// Fields    

	private int id;

	private Users users;

	private Date sdate;
	
	private int lendNo;
	
	private int returnNo;
	
	private int state;

	// Constructors

	/** default constructor */
	public Picturebooks() {
	}

	/** minimal/full constructor */
	public Picturebooks(int id, Users users, Date sdate, int lendNo, int returnNo, int state) {
		this.id = id;
		this.users = users;
		this.sdate = sdate;
		this.lendNo = lendNo;
		this.returnNo = returnNo;
		this.state = state;
	}


	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getSdate() {
		return this.sdate;
	}

	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}
	
	public int getLendNo() {
		return this.lendNo;
	}

	public void setLendNo(int lendNo) {
		this.lendNo = lendNo;
	}
	
	public int getReturnNo() {
		return this.returnNo;
	}

	public void setReturnNo(int returnNo) {
		this.returnNo = returnNo;
	}
	
	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
	}

}
