package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8


/**
 * Archive generated by hbm2java
 */
public class Places implements java.io.Serializable {

	// Fields    

	private int id;

	private String zip;

	private String city;

	// Constructors

	/** default constructor */
	public Places() {
	}

	/** minimal constructor */
	public Places(int id) {
		this.id = id;
	}

	/** full constructor */
	public Places(int id, String zip, String city) {
		this.id = id;
		this.zip = zip;
		this.city = city;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

}
