package com.gint.app.bisis4.client.circ.model;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8



/**
 * Podlokacija generated by hbm2java
 */
public class Podlokacija implements java.io.Serializable {

  // Fields    

  private String podlokacijaId;

  private String podlokacijaOpis;

  private Set primercis = new HashSet(0);

  private Set godines = new HashSet(0);

  // Constructors

  /** default constructor */
  public Podlokacija() {
  }

  /** minimal constructor */
  public Podlokacija(String podlokacijaId, String podlokacijaOpis) {
    this.podlokacijaId = podlokacijaId;
    this.podlokacijaOpis = podlokacijaOpis;
  }

  /** full constructor */
  public Podlokacija(String podlokacijaId, String podlokacijaOpis,
      Set primercis, Set godines) {
    this.podlokacijaId = podlokacijaId;
    this.podlokacijaOpis = podlokacijaOpis;
    this.primercis = primercis;
    this.godines = godines;
  }

  // Property accessors
  public String getPodlokacijaId() {
    return this.podlokacijaId;
  }

  public void setPodlokacijaId(String podlokacijaId) {
    this.podlokacijaId = podlokacijaId;
  }

  public String getPodlokacijaOpis() {
    return this.podlokacijaOpis;
  }

  public void setPodlokacijaOpis(String podlokacijaOpis) {
    this.podlokacijaOpis = podlokacijaOpis;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

  public Set getGodines() {
    return this.godines;
  }

  public void setGodines(Set godines) {
    this.godines = godines;
  }

}
