package com.gint.app.bisis4.client.circ.model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import java.math.BigDecimal;
import java.util.Date;

/**
 * Primerci generated by hbm2java
 */
public class Primerci implements java.io.Serializable {

  // Fields    

  private int primerakId;

  private int version;

  private InternaOznaka internaOznaka;

  private Sigformat sigformat;

  private Odeljenje odeljenje;

  private Povez povez;

  private StatusPrimerka statusPrimerka;

  private NacinNabavke nacinNabavke;

  private Records records;

  private Podlokacija podlokacija;

  private String invBroj;

  private Date datumRacuna;

  private String brojRacuna;

  private String dobavljac;

  private BigDecimal cena;

  private String finansijer;

  private String usmeravanje;

  private String sigDublet;

  private String sigNumerusCurens;

  private String sigUdk;

  private Date datumInventarisanja;

  private String napomene;
  
  private int stanje;

  // Constructors

  /** default constructor */
  public Primerci() {
  }

  /** minimal constructor */
  public Primerci(int primerakId, Records records, String invBroj) {
    this.primerakId = primerakId;
    this.records = records;
    this.invBroj = invBroj;
  }

  /** full constructor */
  public Primerci(int primerakId, InternaOznaka internaOznaka,
      Sigformat sigformat, Odeljenje odeljenje, Povez povez,
      StatusPrimerka statusPrimerka, NacinNabavke nacinNabavke,
      Records records, Podlokacija podlokacija, String invBroj,
      Date datumRacuna, String brojRacuna, String dobavljac, BigDecimal cena,
      String finansijer, String usmeravanje, String sigDublet,
      String sigNumerusCurens, String sigUdk, Date datumInventarisanja,
      String napomene, int stanje) {
    this.primerakId = primerakId;
    this.internaOznaka = internaOznaka;
    this.sigformat = sigformat;
    this.odeljenje = odeljenje;
    this.povez = povez;
    this.statusPrimerka = statusPrimerka;
    this.nacinNabavke = nacinNabavke;
    this.records = records;
    this.podlokacija = podlokacija;
    this.invBroj = invBroj;
    this.datumRacuna = datumRacuna;
    this.brojRacuna = brojRacuna;
    this.dobavljac = dobavljac;
    this.cena = cena;
    this.finansijer = finansijer;
    this.usmeravanje = usmeravanje;
    this.sigDublet = sigDublet;
    this.sigNumerusCurens = sigNumerusCurens;
    this.sigUdk = sigUdk;
    this.datumInventarisanja = datumInventarisanja;
    this.napomene = napomene;
    this.stanje = stanje;
  }

  // Property accessors
  public int getPrimerakId() {
    return this.primerakId;
  }

  public void setPrimerakId(int primerakId) {
    this.primerakId = primerakId;
  }

  public int getVersion() {
    return this.version;
  }

  public void setVersion(int version) {
    this.version = version;
  }

  public InternaOznaka getInternaOznaka() {
    return this.internaOznaka;
  }

  public void setInternaOznaka(InternaOznaka internaOznaka) {
    this.internaOznaka = internaOznaka;
  }

  public Sigformat getSigformat() {
    return this.sigformat;
  }

  public void setSigformat(Sigformat sigformat) {
    this.sigformat = sigformat;
  }

  public Odeljenje getOdeljenje() {
    return this.odeljenje;
  }

  public void setOdeljenje(Odeljenje odeljenje) {
    this.odeljenje = odeljenje;
  }

  public Povez getPovez() {
    return this.povez;
  }

  public void setPovez(Povez povez) {
    this.povez = povez;
  }

  public StatusPrimerka getStatusPrimerka() {
    return this.statusPrimerka;
  }

  public void setStatusPrimerka(StatusPrimerka statusPrimerka) {
    this.statusPrimerka = statusPrimerka;
  }

  public NacinNabavke getNacinNabavke() {
    return this.nacinNabavke;
  }

  public void setNacinNabavke(NacinNabavke nacinNabavke) {
    this.nacinNabavke = nacinNabavke;
  }

  public Records getRecords() {
    return this.records;
  }

  public void setRecords(Records records) {
    this.records = records;
  }

  public Podlokacija getPodlokacija() {
    return this.podlokacija;
  }

  public void setPodlokacija(Podlokacija podlokacija) {
    this.podlokacija = podlokacija;
  }

  public String getInvBroj() {
    return this.invBroj;
  }

  public void setInvBroj(String invBroj) {
    this.invBroj = invBroj;
  }

  public Date getDatumRacuna() {
    return this.datumRacuna;
  }

  public void setDatumRacuna(Date datumRacuna) {
    this.datumRacuna = datumRacuna;
  }

  public String getBrojRacuna() {
    return this.brojRacuna;
  }

  public void setBrojRacuna(String brojRacuna) {
    this.brojRacuna = brojRacuna;
  }

  public String getDobavljac() {
    return this.dobavljac;
  }

  public void setDobavljac(String dobavljac) {
    this.dobavljac = dobavljac;
  }

  public BigDecimal getCena() {
    return this.cena;
  }

  public void setCena(BigDecimal cena) {
    this.cena = cena;
  }

  public String getFinansijer() {
    return this.finansijer;
  }

  public void setFinansijer(String finansijer) {
    this.finansijer = finansijer;
  }

  public String getUsmeravanje() {
    return this.usmeravanje;
  }

  public void setUsmeravanje(String usmeravanje) {
    this.usmeravanje = usmeravanje;
  }

  public String getSigDublet() {
    return this.sigDublet;
  }

  public void setSigDublet(String sigDublet) {
    this.sigDublet = sigDublet;
  }

  public String getSigNumerusCurens() {
    return this.sigNumerusCurens;
  }

  public void setSigNumerusCurens(String sigNumerusCurens) {
    this.sigNumerusCurens = sigNumerusCurens;
  }

  public String getSigUdk() {
    return this.sigUdk;
  }

  public void setSigUdk(String sigUdk) {
    this.sigUdk = sigUdk;
  }

  public Date getDatumInventarisanja() {
    return this.datumInventarisanja;
  }

  public void setDatumInventarisanja(Date datumInventarisanja) {
    this.datumInventarisanja = datumInventarisanja;
  }

  public String getNapomene() {
    return this.napomene;
  }

  public void setNapomene(String napomene) {
    this.napomene = napomene;
  }

	public int getStanje() {
		return stanje;
	}
	
	public void setStanje(int stanje) {
		this.stanje = stanje;
	}

}
