package com.gint.app.bisis4.client.circ.model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Date;
import java.util.Set;

/**
 * Records generated by hbm2java
 */
public class Records implements java.io.Serializable {

  // Fields    

  private int recordId;

  private int pubType;

  private String creator;

  private String modifier;

  private Date dateCreated;

  private Date dateModified;

  private Integer archived;

  private String inUseBy;

  private String content;

  private Set primercis = new HashSet(0);

  private Set godines = new HashSet(0);

  // Constructors

  /** default constructor */
  public Records() {
  }

  /** minimal constructor */
  public Records(int recordId, int pubType, String creator, Date dateCreated) {
    this.recordId = recordId;
    this.pubType = pubType;
    this.creator = creator;
    this.dateCreated = dateCreated;
  }

  /** full constructor */
  public Records(int recordId, int pubType, String creator, String modifier,
      Date dateCreated, Date dateModified, Integer archived, String inUseBy,
      String content, Set primercis, Set godines) {
    this.recordId = recordId;
    this.pubType = pubType;
    this.creator = creator;
    this.modifier = modifier;
    this.dateCreated = dateCreated;
    this.dateModified = dateModified;
    this.archived = archived;
    this.inUseBy = inUseBy;
    this.content = content;
    this.primercis = primercis;
    this.godines = godines;
  }

  // Property accessors
  public int getRecordId() {
    return this.recordId;
  }

  public void setRecordId(int recordId) {
    this.recordId = recordId;
  }

  public int getPubType() {
    return this.pubType;
  }

  public void setPubType(int pubType) {
    this.pubType = pubType;
  }

  public String getCreator() {
    return this.creator;
  }

  public void setCreator(String creator) {
    this.creator = creator;
  }

  public String getModifier() {
    return this.modifier;
  }

  public void setModifier(String modifier) {
    this.modifier = modifier;
  }

  public Date getDateCreated() {
    return this.dateCreated;
  }

  public void setDateCreated(Date dateCreated) {
    this.dateCreated = dateCreated;
  }

  public Date getDateModified() {
    return this.dateModified;
  }

  public void setDateModified(Date dateModified) {
    this.dateModified = dateModified;
  }

  public Integer getArchived() {
    return this.archived;
  }

  public void setArchived(Integer archived) {
    this.archived = archived;
  }

  public String getInUseBy() {
    return this.inUseBy;
  }

  public void setInUseBy(String inUseBy) {
    this.inUseBy = inUseBy;
  }

  public String getContent() {
    return this.content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

  public Set getGodines() {
    return this.godines;
  }

  public void setGodines(Set godines) {
    this.godines = godines;
  }

}
