package com.gint.app.bisis4.client.circ.model;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8


/**
 * Sigformat generated by hbm2java
 */
public class Sigformat implements java.io.Serializable {

  // Fields    

  private String sigFormatId;

  private String formatOpis;

  private Set primercis = new HashSet(0);

  private Set godines = new HashSet(0);

  // Constructors

  /** default constructor */
  public Sigformat() {
  }

  /** minimal constructor */
  public Sigformat(String sigFormatId, String formatOpis) {
    this.sigFormatId = sigFormatId;
    this.formatOpis = formatOpis;
  }

  /** full constructor */
  public Sigformat(String sigFormatId, String formatOpis, Set primercis,
      Set godines) {
    this.sigFormatId = sigFormatId;
    this.formatOpis = formatOpis;
    this.primercis = primercis;
    this.godines = godines;
  }

  // Property accessors
  public String getSigFormatId() {
    return this.sigFormatId;
  }

  public void setSigFormatId(String sigFormatId) {
    this.sigFormatId = sigFormatId;
  }

  public String getFormatOpis() {
    return this.formatOpis;
  }

  public void setFormatOpis(String formatOpis) {
    this.formatOpis = formatOpis;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

  public Set getGodines() {
    return this.godines;
  }

  public void setGodines(Set godines) {
    this.godines = godines;
  }

}
