package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Signing generated by hbm2java
 */
public class Signing implements java.io.Serializable {

	// Fields    

	private int id;

	private Location location;

	private Users users;

	private Date signDate;

	private Date untilDate;

	private Double cost;

	private String receiptId;
  
  private String librarian;


	// Constructors

	/** default constructor */
	public Signing() {
	}

	/** minimal constructor */
	public Signing(int id, Location location, String librarian, Users users,
			Date signDate) {
		this.id = id;
		this.location = location;
		this.librarian = librarian;
		this.users = users;
		this.signDate = signDate;
	}

	/** full constructor */
	public Signing(int id, Location location, String librarian, Users users,
			Date signDate, Date untilDate, Double cost, String receiptId) {
		this.id = id;
		this.location = location;
		this.librarian = librarian;
		this.users = users;
		this.signDate = signDate;
		this.untilDate = untilDate;
		this.cost = cost;
		this.receiptId = receiptId;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getLibrarian() {
		return this.librarian;
	}

	public void setLibrarian(String librarian) {
		this.librarian = librarian;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getSignDate() {
		return this.signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public Date getUntilDate() {
		return this.untilDate;
	}

	public void setUntilDate(Date untilDate) {
		this.untilDate = untilDate;
	}

	public Double getCost() {
		return this.cost;
	}

	public void setCost(Double cost) {
		this.cost = cost;
	}

	public String getReceiptId() {
		return this.receiptId;
	}

	public void setReceiptId(String receiptId) {
		this.receiptId = receiptId;
	}

}
