package com.gint.app.bisis4.client.circ.model;

import java.util.HashSet;
import java.util.Set;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8


/**
 * StatusPrimerka generated by hbm2java
 */
public class StatusPrimerka implements java.io.Serializable {

  // Fields    

  private char statusId;

  private String statusOpis;

  private int zaduziv;

  private Set sveskes = new HashSet(0);

  private Set primercis = new HashSet(0);

  // Constructors

  /** default constructor */
  public StatusPrimerka() {
  }

  /** minimal constructor */
  public StatusPrimerka(char statusId, String statusOpis, int zaduziv) {
    this.statusId = statusId;
    this.statusOpis = statusOpis;
    this.zaduziv = zaduziv;
  }

  /** full constructor */
  public StatusPrimerka(char statusId, String statusOpis, int zaduziv,
      Set sveskes, Set primercis) {
    this.statusId = statusId;
    this.statusOpis = statusOpis;
    this.zaduziv = zaduziv;
    this.sveskes = sveskes;
    this.primercis = primercis;
  }

  // Property accessors
  public char getStatusId() {
    return this.statusId;
  }

  public void setStatusId(char statusId) {
    this.statusId = statusId;
  }

  public String getStatusOpis() {
    return this.statusOpis;
  }

  public void setStatusOpis(String statusOpis) {
    this.statusOpis = statusOpis;
  }

  public int getZaduziv() {
    return this.zaduziv;
  }

  public void setZaduziv(int zaduziv) {
    this.zaduziv = zaduziv;
  }

  public Set getSveskes() {
    return this.sveskes;
  }

  public void setSveskes(Set sveskes) {
    this.sveskes = sveskes;
  }

  public Set getPrimercis() {
    return this.primercis;
  }

  public void setPrimercis(Set primercis) {
    this.primercis = primercis;
  }

}
