package com.gint.app.bisis4.client.circ.model;

// Generated Jan 11, 2007 11:36:46 AM by Hibernate Tools 3.2.0.beta8

/**
 * TipoviObrade generated by hbm2java
 */
public class TipoviObrade implements java.io.Serializable {

  // Fields    

  private int tipobrId;

  private String tipobrSpec;

  // Constructors

  /** default constructor */
  public TipoviObrade() {
  }

  /** full constructor */
  public TipoviObrade(int tipobrId, String tipobrSpec) {
    this.tipobrId = tipobrId;
    this.tipobrSpec = tipobrSpec;
  }

  // Property accessors
  public int getTipobrId() {
    return this.tipobrId;
  }

  public void setTipobrId(int tipobrId) {
    this.tipobrId = tipobrId;
  }

  public String getTipobrSpec() {
    return this.tipobrSpec;
  }

  public void setTipobrSpec(String tipobrSpec) {
    this.tipobrSpec = tipobrSpec;
  }

}
