package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	// Fields    

	private int sysId;

	private MmbrTypes mmbrTypes;

	private EduLvl eduLvl;

	private UserCategs userCategs;

	private Organization organization;

	private Groups groups;

	private Languages languages;

	private String userId;

	private String firstName;

	private String lastName;

	private String parentName;

	private String address;

	private String city;

	private Integer zip;

	private String phone;

	private String email;

	private String jmbg;

	private Integer docId;

	private String docNo;

	private String docCity;

	private String country;

	private String gender;

	private String age;

	private String secAddress;

	private Integer secZip;

	private String secCity;

	private String secPhone;

	private String note;

	private String interests;

	private Integer warningInd;

	private String occupation;

	private String title;

	private String indexNo;

	private Integer classNo;

	private String pass;
  
  private String blockReasons;

	private Set lendings = new HashSet(0);
  
  private Set alllendings = new HashSet(0);

	private Set signings = new HashSet(0);

	private Set duplicates = new HashSet(0);
	
	private Set picturebooks = new HashSet(0);

	// Constructors

	/** default constructor */
	public Users() {
	}

	/** minimal constructor */
	public Users(int sysId, String userId) {
		this.sysId = sysId;
		this.userId = userId;
	}

	/** full constructor */
	public Users(int sysId, MmbrTypes mmbrTypes, EduLvl eduLvl,
			UserCategs userCategs, Organization organization, Groups groups,
			Languages languages, String userId, String firstName,
			String lastName, String parentName, String address, String city,
			Integer zip, String phone, String email, String jmbg,
			Integer docId, String docNo, String docCity, String country,
			String gender, String age, String secAddress, Integer secZip,
			String secCity, String secPhone, String note, String interests,
			Integer warningInd, String occupation, String title,
			String indexNo, Integer classNo, String pass, Set lendings,
      Set signings, Set duplicates) {
		this.sysId = sysId;
		this.mmbrTypes = mmbrTypes;
		this.eduLvl = eduLvl;
		this.userCategs = userCategs;
		this.organization = organization;
		this.groups = groups;
		this.languages = languages;
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.parentName = parentName;
		this.address = address;
		this.city = city;
		this.zip = zip;
		this.phone = phone;
		this.email = email;
		this.jmbg = jmbg;
		this.docId = docId;
		this.docNo = docNo;
		this.docCity = docCity;
		this.country = country;
		this.gender = gender;
		this.age = age;
		this.secAddress = secAddress;
		this.secZip = secZip;
		this.secCity = secCity;
		this.secPhone = secPhone;
		this.note = note;
		this.interests = interests;
		this.warningInd = warningInd;
		this.occupation = occupation;
		this.title = title;
		this.indexNo = indexNo;
		this.classNo = classNo;
		this.pass = pass;
		this.lendings = lendings;
		this.signings = signings;
		this.duplicates = duplicates;
	}

	// Property accessors
	public int getSysId() {
		return this.sysId;
	}

	public void setSysId(int sysId) {
		this.sysId = sysId;
	}

	public MmbrTypes getMmbrTypes() {
		return this.mmbrTypes;
	}

	public void setMmbrTypes(MmbrTypes mmbrTypes) {
		this.mmbrTypes = mmbrTypes;
	}

	public EduLvl getEduLvl() {
		return this.eduLvl;
	}

	public void setEduLvl(EduLvl eduLvl) {
		this.eduLvl = eduLvl;
	}

	public UserCategs getUserCategs() {
		return this.userCategs;
	}

	public void setUserCategs(UserCategs userCategs) {
		this.userCategs = userCategs;
	}

	public Organization getOrganization() {
		return this.organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public Languages getLanguages() {
		return this.languages;
	}

	public void setLanguages(Languages languages) {
		this.languages = languages;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public Integer getZip() {
		return this.zip;
	}

	public void setZip(Integer zip) {
		this.zip = zip;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getJmbg() {
		return this.jmbg;
	}

	public void setJmbg(String jmbg) {
		this.jmbg = jmbg;
	}

	public Integer getDocId() {
		return this.docId;
	}

	public void setDocId(Integer docId) {
		this.docId = docId;
	}

	public String getDocNo() {
		return this.docNo;
	}

	public void setDocNo(String docNo) {
		this.docNo = docNo;
	}

	public String getDocCity() {
		return this.docCity;
	}

	public void setDocCity(String docCity) {
		this.docCity = docCity;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getSecAddress() {
		return this.secAddress;
	}

	public void setSecAddress(String secAddress) {
		this.secAddress = secAddress;
	}

	public Integer getSecZip() {
		return this.secZip;
	}

	public void setSecZip(Integer secZip) {
		this.secZip = secZip;
	}

	public String getSecCity() {
		return this.secCity;
	}

	public void setSecCity(String secCity) {
		this.secCity = secCity;
	}

	public String getSecPhone() {
		return this.secPhone;
	}

	public void setSecPhone(String secPhone) {
		this.secPhone = secPhone;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getInterests() {
		return this.interests;
	}

	public void setInterests(String interests) {
		this.interests = interests;
	}

	public Integer getWarningInd() {
		return this.warningInd;
	}

	public void setWarningInd(Integer warningInd) {
		this.warningInd = warningInd;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getIndexNo() {
		return this.indexNo;
	}

	public void setIndexNo(String indexNo) {
		this.indexNo = indexNo;
	}

	public Integer getClassNo() {
		return this.classNo;
	}

	public void setClassNo(Integer classNo) {
		this.classNo = classNo;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public String getBlockReasons() {
    return blockReasons;
  }

  public void setBlockReasons(String blockReasons) {
    this.blockReasons = blockReasons;
  }

  public Set getLendings() {
		return this.lendings;
	}

	public void setLendings(Set lendings) {
		this.lendings = lendings;
//		Iterator it = this.lendings.iterator();
//		while (it.hasNext()){
//			((Lending)it.next()).setUsers(this);
//		}
	}
  
  public void addLending(Lending lend){
    this.lendings.add(lend);
    lend.setUsers(this);
  }
  
  public void removeLending(Lending lend){
    this.lendings.remove(lend);
    //lend.setUsers(null);
  }
  
  public Set getAlllendings() {
    return this.alllendings;
  }

  public void setAlllendings(Set alllendings) {
    this.alllendings = alllendings;
//    Iterator it = this.alllendings.iterator();
//    while (it.hasNext()){
//      ((Lending)it.next()).setUsers(this);
//    }
  }

	public Set getSignings() {
		return this.signings;
	}

	public void setSignings(Set signings) {
		this.signings = signings;
//		Iterator it = this.signings.iterator();
//		while (it.hasNext()){
//			((Signing)it.next()).setUsers(this);
//		}
	}
  
  public void addSigning(Signing sig){
    this.signings.add(sig);
    sig.setUsers(this);
  }
  
  public void removeSigning(Signing sig){
    this.signings.remove(sig);
    //sig.setUsers(null);
  }

	public Set getDuplicates() {
		return this.duplicates;
	}

	public void setDuplicates(Set duplicates) {
		this.duplicates = duplicates;
//		Iterator it = this.duplicates.iterator();
//		while (it.hasNext()){
//			((Duplicate)it.next()).setUsers(this);
//		}
	}
  
  public void addDuplicate(Duplicate dup){
    this.duplicates.add(dup);
    dup.setUsers(this);
  }
  
  public void removeDuplicate(Duplicate dup){
    this.duplicates.remove(dup);
    //dup.setUsers(null);
  }
  
  public Set getPicturebooks() {
		return this.picturebooks;
	}
  
  public void setPicturebooks(Set picturebooks) {
		this.picturebooks = picturebooks;
//		Iterator it = this.picturebooks.iterator();
//		while (it.hasNext()){
//			((Picturebooks)it.next()).setUsers(this);
//		}
	}
  
  public void addPicturebooks(Picturebooks pic){
    this.picturebooks.add(pic);
    pic.setUsers(this);
  }
  
  public void removePicturebooks(Picturebooks pic){
    this.picturebooks.remove(pic);
    //pic.setUsers(null);
  }
	
}
