package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

import java.util.Date;

/**
 * Warnings generated by hbm2java
 */
public class Warnings implements java.io.Serializable {

	// Fields    

	private int id;

	private Lending lending;

	private WarningTypes warningTypes;

	private Date wdate;

	private String warnNo;

	private Date deadline;

	private String note;

	// Constructors

	/** default constructor */
	public Warnings() {
	}

	/** minimal constructor */
	public Warnings(int id, Lending lending, WarningTypes warningTypes, Date wdate) {
		this.id = id;
		this.lending = lending;
		this.warningTypes = warningTypes;
		this.wdate = wdate;
	}

	/** full constructor */
	public Warnings(int id, Lending lending, WarningTypes warningTypes, Date wdate,
			String warnNo, Date deadline,String note) {
		this.id = id;
		this.lending = lending;
		this.warningTypes = warningTypes;
		this.wdate = wdate;
		this.warnNo = warnNo;
		this.deadline = deadline;
		this.note = note;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Lending getLending() {
		return this.lending;
	}

	public void setLending(Lending lending) {
		this.lending = lending;
	}

	public WarningTypes getWarningTypes() {
		return this.warningTypes;
	}

	public void setWarningTypes(WarningTypes warningTypes) {
		this.warningTypes = warningTypes;
	}

	public Date getWdate() {
		return this.wdate;
	}

	public void setWdate(Date wdate) {
		this.wdate = wdate;
	}

	public String getWarnNo() {
		return this.warnNo;
	}

	public void setWarnNo(String warnNo) {
		this.warnNo = warnNo;
	}

	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
