package com.gint.app.bisis4.client.circ.model;

// Generated Nov 15, 2006 4:24:31 PM by Hibernate Tools 3.2.0.beta8

/**
 * WarnCounters generated by hbm2java
 */
public class WarnCounters implements java.io.Serializable {

	// Fields    

	private int id;

	private WarningTypes warningTypes;

	private int warnYear;

	private Integer lastNo;

	// Constructors

	/** default constructor */
	public WarnCounters() {
	}

	/** minimal constructor */
	public WarnCounters(int id, WarningTypes warningTypes, int warnYear) {
		this.id = id;
		this.warningTypes = warningTypes;
		this.warnYear = warnYear;
	}

	/** full constructor */
	public WarnCounters(int id, WarningTypes warningTypes, int warnYear,
			Integer lastNo) {
		this.id = id;
		this.warningTypes = warningTypes;
		this.warnYear = warnYear;
		this.lastNo = lastNo;
	}

	// Property accessors
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public WarningTypes getWarningTypes() {
		return this.warningTypes;
	}

	public void setWarningTypes(WarningTypes warningTypes) {
		this.warningTypes = warningTypes;
	}

	public int getWarnYear() {
		return this.warnYear;
	}

	public void setWarnYear(int warnYear) {
		this.warnYear = warnYear;
	}

	public Integer getLastNo() {
		return this.lastNo;
	}

	public void setLastNo(Integer lastNo) {
		this.lastNo = lastNo;
	}

}
