CREATE INDEX warn_counters_ibfk_1 ON warn_counters ( wtype );
alter table warn_counters add constraint warn_counters_ibfk_1 foreign key (wtype ) references warning_types (id ) on delete CASCADE on update CASCADE;
CREATE INDEX users_ibfk_5 ON users ( languages );
alter table users add constraint users_ibfk_5 foreign key (languages ) references languages (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX users_ibfk_6 ON users ( organization );
alter table users add constraint users_ibfk_6 foreign key (organization ) references organization (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX users_ibfk_3 ON users ( mmbr_type );
alter table users add constraint users_ibfk_3 foreign key (mmbr_type ) references mmbr_types (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX users_ibfk_4 ON users ( edu_lvl );
alter table users add constraint users_ibfk_4 foreign key (edu_lvl ) references edu_lvl (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX users_ibfk_2 ON users ( user_categ );
alter table users add constraint users_ibfk_2 foreign key (user_categ ) references user_categs (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX users_ibfk_1 ON users ( groups );
alter table users add constraint users_ibfk_1 foreign key (groups ) references groups (sys_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX membership_ibfk_2 ON membership ( mmbr_type );
alter table membership add constraint membership_ibfk_2 foreign key (mmbr_type ) references mmbr_types (id ) on delete CASCADE on update CASCADE;
CREATE INDEX membership_ibfk_1 ON membership ( user_categ );
alter table membership add constraint membership_ibfk_1 foreign key (user_categ ) references user_categs (id ) on delete CASCADE on update CASCADE;
CREATE INDEX signing_ibfk_1 ON signing ( sys_id );
alter table signing add constraint signing_ibfk_1 foreign key (sys_id ) references users (sys_id ) on delete CASCADE on update CASCADE;
CREATE INDEX signing_ibfk_2 ON signing ( location );
alter table signing add constraint signing_ibfk_2 foreign key (location ) references location (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_19 ON godine ( dostupnost_id );
alter table godine add constraint FK_Relationship_19 foreign key (dostupnost_id ) references dostupnost (dostupnost_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_6 ON godine ( nacin_id );
alter table godine add constraint FK_Relationship_6 foreign key (nacin_id ) references nacin_nabavke (nacin_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_5 ON godine ( povez_id );
alter table godine add constraint FK_Relationship_5 foreign key (povez_id ) references povez (povez_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_9 ON godine ( podlokacija_id );
alter table godine add constraint FK_Relationship_9 foreign key (podlokacija_id ) references podlokacija (podlokacija_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_8 ON godine ( IntOzn_id );
alter table godine add constraint FK_Relationship_8 foreign key (IntOzn_id ) references interna_oznaka (IntOzn_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_7 ON godine ( odeljenje_id );
alter table godine add constraint FK_Relationship_7 foreign key (odeljenje_id ) references odeljenje (odeljenje_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_16 ON godine ( SigFormat_ID );
alter table godine add constraint FK_Relationship_16 foreign key (SigFormat_ID ) references sigformat (SigFormat_ID ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_4 ON godine ( record_id );
alter table godine add constraint FK_Relationship_4 foreign key (record_id ) references records (record_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX lending_ibfk_1 ON lending ( sys_id );
alter table lending add constraint lending_ibfk_1 foreign key (sys_id ) references users (sys_id ) on delete CASCADE on update CASCADE;
CREATE INDEX lending_ibfk_2 ON lending ( location );
alter table lending add constraint lending_ibfk_2 foreign key (location ) references location (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX duplicate_ibfk_1 ON duplicate ( sys_id );
alter table duplicate add constraint duplicate_ibfk_1 foreign key (sys_id ) references users (sys_id ) on delete CASCADE on update CASCADE;
CREATE INDEX FK_Relationship_18 ON primerci ( dostupnost_id );
alter table primerci add constraint FK_Relationship_18 foreign key (dostupnost_id ) references dostupnost (dostupnost_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_11 ON primerci ( nacin_id );
alter table primerci add constraint FK_Relationship_11 foreign key (nacin_id ) references nacin_nabavke (nacin_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_10 ON primerci ( povez_id );
alter table primerci add constraint FK_Relationship_10 foreign key (povez_id ) references povez (povez_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_14 ON primerci ( podlokacija_id );
alter table primerci add constraint FK_Relationship_14 foreign key (podlokacija_id ) references podlokacija (podlokacija_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_1 ON primerci ( status_id );
alter table primerci add constraint FK_Relationship_1 foreign key (status_id ) references status_primerka (status_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_13 ON primerci ( IntOzn_id );
alter table primerci add constraint FK_Relationship_13 foreign key (IntOzn_id ) references interna_oznaka (IntOzn_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_12 ON primerci ( odeljenje_id );
alter table primerci add constraint FK_Relationship_12 foreign key (odeljenje_id ) references odeljenje (odeljenje_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_17 ON primerci ( SigFormat_ID );
alter table primerci add constraint FK_Relationship_17 foreign key (SigFormat_ID ) references sigformat (SigFormat_ID ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_2 ON primerci ( record_id );
alter table primerci add constraint FK_Relationship_2 foreign key (record_id ) references records (record_id ) on delete CASCADE on update RESTRICT;
CREATE INDEX picturebooks_ibfk_1 ON picturebooks ( sys_id );
alter table picturebooks add constraint picturebooks_ibfk_1 foreign key (sys_id ) references users (sys_id ) on delete CASCADE on update CASCADE;
CREATE INDEX FK_Relationship_3 ON sveske ( status_id );
alter table sveske add constraint FK_Relationship_3 foreign key (status_id ) references status_primerka (status_id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX FK_Relationship_15 ON sveske ( godina_id );
alter table sveske add constraint FK_Relationship_15 foreign key (godina_id ) references godine (godina_id ) on delete CASCADE on update RESTRICT;
CREATE INDEX warnings_ibfk_1 ON warnings ( wtype );
alter table warnings add constraint warnings_ibfk_1 foreign key (wtype ) references warning_types (id ) on delete RESTRICT on update RESTRICT;
CREATE INDEX warnings_ibfk_2 ON warnings ( lending_id );
alter table warnings add constraint warnings_ibfk_2 foreign key (lending_id ) references lending (id ) on delete RESTRICT on update RESTRICT;
