INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('+', 'Slobodno za razmenu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('-', 'Deziderat', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('1', 'Naručeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('2', 'U obradi', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('3', 'U povezu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('4', 'U reviziji', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('5', 'Preusmereno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('6', 'Oštećeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('7', 'Zagubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('8', 'Izgubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('9', 'Otpisano', 0);

INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('AP', 'analiza poslovanja');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('AZ', 'anali, zbornici');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('BI', 'biblioteksrstvo, bibliografija, informacija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DI', 'Diplomski radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DJ', 'društveno-političko uređenje Jugoslavije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DM', 'diplomski-master radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DO', 'dohodak, raspodela dohotka, lični dohodak');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DR', 'doktorski radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('EF', 'finansije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('EI', 'ekonomska istorija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('EM', 'međunarodni ekonomski i finansijski odnosi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('EP', 'ekonomska politika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('ET', 'ekonomska teorija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('FI', 'filosofija, psihologija, estetika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('GE', 'geografija, privredna geografija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('HP', 'hemija, poznavanje robe');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('II', 'Inteligentni informacioni sistemi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('IO', 'industrija, industrijska organizacija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('IS', 'istorija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('JE', 'jezici, rečnici, lingvistika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('KI', 'kibernetika, informatika, AOP');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('KP', 'književna publicistika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('LE', 'leksikoni, enciklopedije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('MD', 'međunarodni društveno-politički odnosi i društveno-politički sistem');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('MG', 'marketing');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('MP', 'mala privreda, zanatstvo');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('MR', 'magistarski radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('MS', 'matematika, statistika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('NI', 'nauka, naučno-tehnički progres, naučno-istraživački rad');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('NR', 'nauka o radu, rad, radnici');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('OR', 'organizacija rada, produktivnost, automatizacija rada');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('OS', 'ostalo');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PI', 'planiranje, investicije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PO', 'poljoprivreda, poljoprivredne organizacije, prehrambena industrija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PR', 'pravo, privredno pravo');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PŠO', 'prosveta, školstvo, obrazovanje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('RD', 'magistarski, doktorski radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('RK', 'računovodstvo, knjigovotstvo');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('RO', 'radne organizacije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('SD', 'statistička dokumentacija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('SE', 'Softverski inženjering');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('SO', 'sociologija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('SP', 'socijalna politika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('TO', 'trgovina (unutrašnja, spoljna), trgovinske organizacije');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('TS', 'transport, saobraćaj, osiguranje, spoljna trgovina');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('TŽ', 'tržište, cene, ponuda, potražnja, istraživanje tržišta');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('UI', 'Upravljački informacioni sistemi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('UR', 'urbanizam, komunalna delatnost');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('UT', 'ugostiteljstvo, turizam');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('ZR', 'završni radovi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('ZŠ', 'zaštita čovekove sredine');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('DSCG', 'društveno-politički sistem Srbije i Crne Gore');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('E', 'opšta ekonomija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('F', 'filosofija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('I', 'industrija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('J', 'jezici, lingvistika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('K', 'knjigovodstvo');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('M', 'matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('OT', 'organizaciona tehnika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('P', 'poljoprivreda');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PN', 'Prirodne nauke');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('PS', 'psiholigija');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('S', 'statistika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('T', 'trgovina');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('U', 'urbanizam');


INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A1', 'arheografsko odeljenje 1 (br. 20)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A2', 'arheografsko odeljenje 2 (br. 23)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A3', 'arheografsko odeljenje 3 (br. 17)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A4', 'arheografsko odeljenje 4 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A5', 'arheografsko odeljenje 5 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('AG', 'AGRIS');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('B1', 'bibliografija (br. 60)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('IN', 'Ingormacije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M1', 'matično 1');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M2', 'matično 2');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M3', 'matično 3');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M4', 'matično 4');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('N1', 'nabavka');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O1', 'obrada 1 (br. 58)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O2', 'obrada 2 (br. 65)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O3', 'obrada 3 (br. 64)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('P1', 'periodika - obrada (br. 52)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PK', 'posebne zbirke - karte');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PL', 'posebne zbirke - likovni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PM', 'posebne zbirke - muzikalije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PS', 'posebne zbirke - sitno štampa');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RC', 'referalni centar ( priru na )');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RE', 'rezervni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('S1', 'Sekretarijat - arhiva');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U1', 'Upravnik');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U2', 'Pomoćnik upravnika za stručne poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U3', 'Pomoćnik upravnika za opšte poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Z1', 'Zaštita');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č1', 'čitaonica rariteta (br. 18)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č2', 'donja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č3', 'gornja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č4', 'čitaonica posebnih zbirki');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č5', 'čitaonica referalnog centra');

INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('00', 'odeljenje 00');

INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('a', 'kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('b', 'Razmena');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('c', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('d', 'Obavezni primerak');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('e', 'Zatečeni (stari) fond');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('f', 'Sopstvena izdanja');

INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('a', 'Bibliofilski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('b', 'Broširano (tvrde korice, meke korice)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('c', 'Fascikl povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('d', 'Italijanski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('f', 'Platno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('g', 'Poluplatno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('h', 'Polukoža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('i', 'Spiralni povez (npr. kalendar)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('k', 'Veštačka koža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('l', 'Ostali povezi (nove vrste, nenaved. pov, moderni)');

INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('1', 'Vremenski ograničena dostupnost - do 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('2', 'Vremenski ograničena dostupnost - 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('3', 'Vremenski ograničena dostupnost - 14 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('4', 'Delimična dostupnost - čitaonica');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('5', 'Delimična dostupnost - sa dozvolom autora');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('6', 'Sadržaj dokumenta nedostupan (poseban tretman)');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('7', 'Potpuna nedostupnost (arhivski primerak ...)');

INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('00','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('01','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('02','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('03','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('04','nepoznato');

INSERT INTO Counters (counter_name, counter_value) VALUES ('recordid', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('primerakid', 0); 
INSERT INTO Counters (counter_name, counter_value) VALUES ('godinaid', 0);  
INSERT INTO Counters (counter_name, counter_value) VALUES ('sveskaid', 0);  
INSERT INTO Counters (counter_name, counter_value) VALUES ('RN', 0);

INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (1,'<?xml version="1.0"?><process-type name="Monografske - kompletna obrada" pubType="1"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="010a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><initial-subfield name="7004"/><initial-subfield name="700a"/><initial-subfield name="700b"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');
INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (2,'<?xml version="1.0"?><process-type name="Serijske - kompletna obrada" pubType="2"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="011a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="110a"/><initial-subfield name="110b"/><initial-subfield name="110c"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');

INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('admin', 'admin','Bojana', 'Dimiæ','bdimic@uns.ns.ac.yu','napomena', 1, 1, 1, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><process-type name="Serijske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');
INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('circ', 'circ','Danijela','Tesendic','tesendic@uns.ns.ac.yu','', 0, 1, 0, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');


