INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('+', 'Slobodno za razmenu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('-', 'Deziderat', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('1', 'Naručeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('2', 'U obradi', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('3', 'U povezu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('4', 'U reviziji', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('5', 'Preusmereno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('6', 'Oštećeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('7', 'Zagubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('8', 'Izgubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('9', 'Otpisano', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('A', 'Aktivno', 1);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('R', '***', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('K', '***', 0);

INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CD', 'CD');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CDm', 'Compact Disc');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('D', 'Fizika-diplomski');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('F', 'Fizika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Fc', 'Fizika-casopisi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Fs', 'Separati - fizika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('M', 'Matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('M1', 'Matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Mc', 'Matematika casopisi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Md', 'Matematika-diplomski');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Ms', 'Separati - matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('C', 'Casopisi opsti fond');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CDc', 'CD Casopisi');

INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A1', 'arheografsko odeljenje 1 (br. 20)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A2', 'arheografsko odeljenje 2 (br. 23)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A3', 'arheografsko odeljenje 3 (br. 17)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A4', 'arheografsko odeljenje 4 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A5', 'arheografsko odeljenje 5 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('AG', 'AGRIS');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('B1', 'bibliografija (br. 60)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('IN', 'Ingormacije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M1', 'matično 1');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M2', 'matično 2');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M3', 'matično 3');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M4', 'matično 4');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('N1', 'nabavka');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O1', 'obrada 1 (br. 58)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O2', 'obrada 2 (br. 65)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O3', 'obrada 3 (br. 64)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('P1', 'periodika - obrada (br. 52)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PK', 'posebne zbirke - karte');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PL', 'posebne zbirke - likovni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PM', 'posebne zbirke - muzikalije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PS', 'posebne zbirke - sitno štampa');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RC', 'referalni centar ( priru na )');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RE', 'rezervni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('S1', 'Sekretarijat - arhiva');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U1', 'Upravnik');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U2', 'Pomoćnik upravnika za stručne poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U3', 'Pomoćnik upravnika za opšte poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Z1', 'Zaštita');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č1', 'čitaonica rariteta (br. 18)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č2', 'donja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č3', 'gornja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č4', 'čitaonica posebnih zbirki');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č5', 'čitaonica referalnog centra');

INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('01', 'Dečje');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('02', 'Odrasli');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('03', 'Stručne knjige i čitaonica');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('04', 'Banatska Topola');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('05', 'Banatsko Veliko Selo');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('06', 'Bašaid');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('07', 'Idjoš');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('08', 'Mokrin');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('09', 'Nakovo');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('10', 'Novi Kozarci');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('11', 'Rusko Selo');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('12', 'Sajan');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('13', 'Zavičajna zbirka');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('14', '***');

INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('a', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('b', 'Razmena');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('c', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('d', 'Obavezni primerak');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('e', 'Zatečeni (stari) fond');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('f', 'Sopstvena izdanja');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('k', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('o', 'Otkup');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('p', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('s', 'Sopstvena izdanja');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('r', '***');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('m', '***');

INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('a', 'Bibliofilski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('b', 'Broširano (tvrde korice, meke korice)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('c', 'Fascikl povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('d', 'Italijanski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('f', 'Platno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('g', 'Poluplatno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('h', 'Polukoža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('i', 'Spiralni povez (npr. kalendar)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('k', 'Veštačka koža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('l', 'Ostali povezi (nove vrste, nenaved. pov, moderni)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('m', 'Meki povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('t', 'Tvrdi povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('n', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('p', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('2', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('7', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('6', '***');

INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('1', 'Vremenski ograničena dostupnost - do 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('2', 'Vremenski ograničena dostupnost - 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('3', 'Vremenski ograničena dostupnost - 14 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('4', 'Delimična dostupnost - čitaonica');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('5', 'Delimična dostupnost - sa dozvolom autora');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('6', 'Sadržaj dokumenta nedostupan (poseban tretman)');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('7', 'Potpuna nedostupnost (arhivski primerak ...)');

INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('1', 'Format I');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('2', 'Format II'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('3', 'Format III'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('4', 'Format IV'); 

INSERT INTO Counters (counter_name, counter_value) VALUES ('recordid', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('primerakid', 0); 
INSERT INTO Counters (counter_name, counter_value) VALUES ('godinaid', 0);  
INSERT INTO Counters (counter_name, counter_value) VALUES ('sveskaid', 0);  


INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (1,'<?xml version="1.0"?><process-type name="Monografske - kompletna obrada" pubType="1"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="010a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><initial-subfield name="7004"/><initial-subfield name="700a"/><initial-subfield name="700b"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');
INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (2,'<?xml version="1.0"?><process-type name="Serijske - kompletna obrada" pubType="2"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="011a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="110a"/><initial-subfield name="110b"/><initial-subfield name="110c"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');

INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('admin', 'admin','Bojana', 'Dimi�','bdimic@uns.ns.ac.yu','napomena', 1, 1, 1, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><process-type name="Serijske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');
INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('circ', 'circ','Danijela','Tesendic','tesendic@uns.ns.ac.yu','', 0, 1, 0, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');

