INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('0', 'Nepoznat', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('1', 'Aktivan fond', 1);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('2', 'Aktivan fond', 1);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('3', 'Na koričenju', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('4', 'Oštećena jedinica', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('5', 'Vraćeno u nabavno - neispravan primerak', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('6', 'Rashodovano', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('7', 'Na obradi', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('8', 'Suvišak', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('9', 'Depozit', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('A', 'Tr.vr. – predlog za rashod', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('B', 'Tužbe ´88-´03', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('C', 'autorski katalog', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('K', 'stručni katalog', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('N', 'neaktelno -predlog za rashod', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('P', 'predmetni katalog', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('i', 'inventar - za ekspediciju', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('S', 'Slobodno', 1);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('Z', 'Zauzeto', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('U', 'Status U', 0);


INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('B', 'Zavičajni fond - Beograd');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('BL', 'Bibliotekarstvo');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('BLS', 'Bibliotekarstvo - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('BPR', 'Beogradika - priručnici');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('BPS', 'Beogradika - priručnici - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('BS', 'Beogradika - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('CD', 'Interna oznaka CD');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('D', 'Dečji fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DEP', 'Depozit');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DF', 'Dijafilmovi');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DP', 'Dečje - priručnici');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DPS', 'Dečje - priručnici - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DR', 'Dečje - retka knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DRS', 'Dečje - retka knjiga - strana');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('DS', 'Dečje - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('F', 'Fotografije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FA', 'Fotografije - zavičajni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FI', 'Interna oznaka FI');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FD', 'Interna oznaka FD');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FM', 'Film');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FMS', 'Film - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FS', 'Fotografija - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('FTI', 'Fototipska izdanja');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('G', 'Gramofonske ploče');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('GK', 'Geografske karte');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('IB', 'Izdavanje - Beograd');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('IBS', 'Izdavanje - Beograd - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('K', 'Kasete');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('L', 'Legat');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M', 'Muzika - knjige');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('MM', 'Interna oznaka MM');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('MF', 'Mikrofilmovi');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('MS', 'Muzika - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O', 'Referalna zbirka');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('OS', 'Referalna zbirka - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('P', 'Pozorište');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PBL', 'Periodika bibliografije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PF', 'Pokretni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PFS', 'Pokretni fond - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PK', 'Plakati');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PN', 'Priručnici - nabavno');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PNS', 'Priručnici - nabavno - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PPR', 'Periodika - priručnici');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PPS', 'Periodika - priručnici - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PS', 'Pozorište - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('R', 'Rukopisi');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RI', 'Retka izdanja');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RIS', 'Retka izdanja - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('SI', 'Interna oznaka SI');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U', 'Umetnost');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('US', 'Umetnost - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('X', 'Opšti fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('XS', 'Opšti fond - strana knjiga');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Š', 'Šah');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('ŠS', 'Šah - strana knjiga');



INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('i', 'izdanja BGB');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('l', 'poklon izdavaca');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('m', 'marketing');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('n', 'obavezni primerak NBS');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('r', 'republicki otkup');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('t', 'zateceno');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('z', 'zamena');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('a', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('b', 'Razmena');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('c', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('d', 'Obavezni primerak');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('e', 'Zatečeni (stari) fond');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('f', 'Sopstvena izdanja');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('k', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('o', 'Otkup');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('p', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('s', 'Sopstvena izdanja');

INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('a', 'Bibliofilski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('b', 'Broširano (tvrde korice, meke korice)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('c', 'Fascikl povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('d', 'Italijanski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('f', 'Platno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('g', 'Poluplatno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('h', 'Polukoža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('i', 'Spiralni povez (npr. kalendar)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('k', 'Veštačka koža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('l', 'Ostali povezi (nove vrste, nenaved. pov, moderni)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('m', 'Meki povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('t', 'Tvrdi povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('P', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('B', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('BH', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('D', '***');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('O', '***');

INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('11', 'Odeljenje 11');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('01', 'Odeljenje 01');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('02', 'Odeljenje 02');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('03', 'Odeljenje 03');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('04', 'Odeljenje 04');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('99', 'Odeljenje 99');

INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('001', 'Biblioteka grada Beograda, Pult');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('002', 'BGB - Dečje o. "Čika Jova Zmaj"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('003', 'BGB - Dečje o. "Neven"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('004', 'BGB - Američki kutak');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('005', 'BGB-Periodika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('100', 'Vožd - B. "Dositej Obradović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('101', 'Vožd - B. "Dositej Obradović", Dečje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('102', 'Vožd - og. "Milorad Panić Surep"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('103', 'Vožd - og. "Karađorđe"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('104', 'Vožd - og. "Milutin Uskoković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('105', 'Vožd - og. "Stepa Stepanović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('106', 'Vožd - og. "Filip Višnjić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('107', 'Vožd - og. "Milan Đ. Milićević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('120', 'Vrač - B. "Petar Kočić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('121', 'Vrač - Dečje odeljenje "Rastko"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('122', 'Vrač - og. "Borislav Pekić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('123', 'Vrač - og. "Laza Lazarević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('124', 'Vrač - og. "Slobodan Marković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('140', 'Zvez - B. "Vuk Karadžić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('141', 'Zvez - og. "Radoje Domanović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('142', 'Zvez - og. "Blažo Šćepanović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('143', 'Zvez - og. "Stanislav Vinaver"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('144', 'Zvez - og. "Dragiša Vitošević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('145', 'Zvez - og. "Branko Miljković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('146', 'Zvez - og. "Jefimija"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('147', 'Zvez � og. "Moma Dimić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('160', 'Čuka - B. "Laza Kostić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('161', 'Čuka - og. "Prometej"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('162', 'ZATVOREN OGRANAK');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('163', 'Čuka - og. "Branko Ćopić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('164', 'Čuka - og. "Đura Jakšić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('165', 'Čuka - og. "Dimitrije Tucović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('166', 'Čuka - og. "Duško Radović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('167', 'Čuka - og. "Rušanj"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('168', 'Čuka - og. "Ostružnica"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('180', 'Rako - B. "Miodrag Bulatović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('181', 'Rako - og. "Miroslav Antić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('182', 'Rako - og. "Dušan Matić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('183', 'Rako - og. "Ivo Andrić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('184', 'Rako - og. "Miloš Crnjanski"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('185', 'Rako - og. "Isidora Sekulić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('200', 'Mlad - B. "Despot Stefan Lazarević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('201', 'Mlad - Dečje odeljenje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('220', 'Bara - B. "Jovan Dučić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('221', 'Bara - og. "Vranić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('222', 'Bara - og. "Branko Radičević", Meljak');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('240', 'Savv - B. "Isidora Sekulić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('241', 'Savv - Dečje odeljenje "Vojislav Ilić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('242', 'Savv - og. "Jovan Jovanović Zmaj"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('243', 'Savv - og. "Veselin Masleša"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('244', 'Savv - og. "Bora Stanković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('245', 'Savv - og. "Veljko Petrović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('246', 'Savv - punkt BIP');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('260', 'Stag - B. "Đorđe Jovanović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('261', 'Stag - Dečje odeljenje "Dragan Lukić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('262', 'Stag - og. "Jovan Popović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('263', 'Stag - punkt "Energogas"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('280', 'NBgd - B. "Vuk Karadžić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('281', 'NBgd - og. "Fontana"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('282', 'NBgd - og. "Vladan Desnica"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('283', 'NBgd - og. "Marija Ilić-Agapova"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('284', 'NBgd - og. "Bežanija"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('285', 'NBgd - og. "Pero Slijepčević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('286', 'NBgd - og. "Meša Selimović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('287', 'NBgd - og. "Sava"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('288', 'NBgd - og. "Vasko Popa"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('289', 'NBgd - Dečje odeljenje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('290', 'NBgd - og. "Pionir"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('310', 'Zemu - B. "Sveti Sava"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('311', 'Zemu - Dečje odeljenje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('312', 'Zemu - og. "Gornji grad"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('313', 'Zemu - og. "Zemun Polje"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('314', 'Zemu - og. "Karađorđev trg"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('315', 'Zemu - og. "Novi grad"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('316', 'Zemu - og. "Batajnica"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('317', 'Zemu - og. "Dobanovci"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('318', 'Zemu - og. "Surčin"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('319', 'Zemu - og. "Nova Galenika"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('330', 'Groc - B. "Ilija Garašanin"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('331', 'Groc - Dečje odeljenje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('332', 'Groc - og. "Vrčin"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('333', 'Groc - og. "Kaluđerica"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('350', 'Sopo - B. "Milovan Vidaković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('351', 'Sopo - og. "Mali Požarevac"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('352', 'Sopo - og. "Ralja"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('353', 'Sopo - og. "Rogača"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('400', 'Pali - B. "Milutin Bojić"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('401', 'Pali - og. "Hadžipopovac"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('402', 'Pali - og. "Stara Karaburma"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('403', 'Pali - og. "Pero Ćetković"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('404', 'Pali - og. "Marijana Gregoran"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('405', 'Pali - og. "Padinska skela"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('406', 'Pali - og. "Borča"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('407', 'Pali - og. "Kotež"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('408', 'Pali - og. "Ovča"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('409', 'Pali - og. "Krnjača"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('410', 'Pali - og. "Novo naselje"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('420', 'Laza - B. "Dimitrije Tucović"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('421', 'Laza - B. "Dimitrije Tucović", Dečje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('422', 'Laza - og. u Velikim Crljenima');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('423', 'Laza - og. u Rudovcima');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('424', 'Laza - og. u Junkovcu');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('440', 'Obre - B. "Vlada Aksentijević"');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('441', 'Obre - og. u JP za informisanje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('442', 'Obre - og. u Rojkovcu');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('443', 'Obre - og. u Drenu');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('444', 'Obre - og. u Stublinama');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('445', 'Obre - Dečje odeljenje');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('999', 'Član udruženih biblioteka');



INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('1', 'Vremenski ograničena dostupnost - do 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('2', 'Vremenski ograničena dostupnost - 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('3', 'Vremenski ograničena dostupnost - 14 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('4', 'Delimična dostupnost - čitaonica');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('5', 'Delimična dostupnost - sa dozvolom autora');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('6', 'Sadržaj dokumenta nedostupan (poseban tretman)');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('7', 'Potpuna nedostupnost (arhivski primerak ...)');

INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('I', 'Format I');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('II', 'Format II'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('III', 'Format III'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('IV', 'Format IV');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('X', 'Format X');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('IX', 'Format IX'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('i', 'Format i'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ii', 'Format ii');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('XS', 'Format XS');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('MM', 'Format MM');


INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('00','Inventarna knjiga 00');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('20','Inventarna knjiga 20');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('30','Inventarna knjiga 30');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('25','Inventarna knjiga 25');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('60','Inventarna knjiga 60');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('21','Inventarna knjiga 21');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('03','Inventarna knjiga 03');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('10','Inventarna knjiga 10');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('02','Inventarna knjiga 02');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('06','Inventarna knjiga 06');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('12','Inventarna knjiga 12');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('07','Inventarna knjiga 07');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('63','Inventarna knjiga 63');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('01','Inventarna knjiga 01');

INSERT INTO Counters (counter_name, counter_value) VALUES ('recordid', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('RN', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('primerakid', 0); 
INSERT INTO Counters (counter_name, counter_value) VALUES ('godinaid', 0);  
INSERT INTO Counters (counter_name, counter_value) VALUES ('sveskaid', 0);

INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (1,'<?xml version="1.0"?><process-type name="Monografske - kompletna obrada" pubType="1"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="010a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><initial-subfield name="7004"/><initial-subfield name="700a"/><initial-subfield name="700b"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');
INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (2,'<?xml version="1.0"?><process-type name="Serijske - kompletna obrada" pubType="2"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="011a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="110a"/><initial-subfield name="110b"/><initial-subfield name="110c"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');

INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('admin', 'admin','Bojana', 'Dimi�','bdimic@uns.ns.ac.yu','napomena', 1, 1, 1, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><process-type name="Serijske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');
INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('circ', 'circ','Danijela','Tesendic','tesendic@uns.ns.ac.yu','', 0, 1, 0, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');

