INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('+', 'Slobodno za razmenu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('-', 'Deziderat', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('1', 'Naručeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('2', 'U obradi', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('3', 'U povezu', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('4', 'U reviziji', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('5', 'Preusmereno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('6', 'Oštećeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('7', 'Zagubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('8', 'Izgubljeno', 0);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('9', 'Otpisano', 2);
INSERT INTO Status_Primerka (Status_ID, Status_Opis, Zaduziv) VALUES ('A', 'Aktivno', 1);


INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CD', 'CD');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CDm', 'Compact Disc');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('D', 'Fizika-diplomski');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('F', 'Fizika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Fc', 'Fizika-casopisi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Fs', 'Separati - fizika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('M', 'Matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('M1', 'Matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Mc', 'Matematika casopisi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Md', 'Matematika-diplomski');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('Ms', 'Separati - matematika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('C', 'Casopisi opsti fond');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('CDc', 'CD Casopisi');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('s', 'Tekuća periodika');
INSERT INTO Podlokacija (Podlokacija_ID, Podlokacija_Opis) VALUES ('sr', 'Raritetna periodika');

INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A1', 'arheografsko odeljenje 1 (br. 20)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A2', 'arheografsko odeljenje 2 (br. 23)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A3', 'arheografsko odeljenje 3 (br. 17)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A4', 'arheografsko odeljenje 4 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('A5', 'arheografsko odeljenje 5 (potkrovlje)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('AG', 'AGRIS');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('B1', 'bibliografija (br. 60)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('IN', 'Ingormacije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M1', 'matično 1');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M2', 'matično 2');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M3', 'matično 3');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('M4', 'matično 4');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('N1', 'nabavka');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O1', 'obrada 1 (br. 58)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O2', 'obrada 2 (br. 65)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('O3', 'obrada 3 (br. 64)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('P1', 'periodika - obrada (br. 52)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PK', 'posebne zbirke - karte');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PL', 'posebne zbirke - likovni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PM', 'posebne zbirke - muzikalije');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('PS', 'posebne zbirke - sitno štampa');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RC', 'referalni centar ( priru na )');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('RE', 'rezervni fond');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('S1', 'Sekretarijat - arhiva');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U1', 'Upravnik');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U2', 'Pomoćnik upravnika za stručne poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('U3', 'Pomoćnik upravnika za opšte poslove');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Z1', 'Zaštita');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č1', 'čitaonica rariteta (br. 18)');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č2', 'donja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č3', 'gornja čitaonica');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č4', 'čitaonica posebnih zbirki');
INSERT INTO Interna_oznaka (IntOzn_ID, IntOzn_Opis) VALUES ('Č5', 'čitaonica referalnog centra');

INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('01', 'Đura Daničić, Dunavska 1, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('02', 'Stevan Sremac, Narodnih heroja 19, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('03', 'Petefi Šandor, Jožefa Atile 16, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('04', 'Toša Trifunov, Kralja Petra I 1, Begeč');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('05', 'Kosta Trifković, Braće Mogin 2, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('06', 'Jovan Jovanović Zmaj, Kralja Petra I 1, Sremska Kamenica');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('07', 'Dečje odelenje, Dunavska 1, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('08', 'Vidovdansko naselje');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('09', 'Petar Kočić, Poslovni centar, Veternik');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('10', 'Milica Stojadinović Srpkinja, Vidovdanska 17, Bukovac');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('11', 'Đorđe Aracki, Zmaj Jovina 17, Ledinci');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('12', 'Majur');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('13', 'Mihal Babinka, Slovačka 49, Kisač');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('14', 'Endre Adi, Vojvođanska 73, Budisava');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('15', '7. jul');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('16', 'Nikola Tesla, Vojvode Putnika 9, Stepanovićevo');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('17', 'Jovan Jovanović Zmaj, Cara Lazara 42, Futog');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('18', 'Đura Jakšić, Kralja Petra I 4, Kać');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('19', 'Veljko Petrović, Zadružna 17, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('20', 'Laza Kostić, Laze Kostića 32, Kovilj');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('21', 'Rumunska baza');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('22', 'Vladimir Nazor, Koste Nađa 1, Petrovaradin');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('23', 'Čitaonica');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('24', 'Medicinska škola');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('25', 'Branko Radičević, Karlovačkih đaka 4, Sremski Karlovci');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('26', 'Žarko Zrenjanin, Dušana Danilovića 12, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('27', 'Danilo Kiš, Narodnog fronta 47, Novi Sad');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('28', 'Ivo Andrić, Arsenija Čarnojevića 24, Rumenka');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('29', 'Serijske publikacije');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('30', 'Knjigobus');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('31', 'Zavičajna zbirka');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('39', 'B fond');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('no', 'Nabavno - obradno');
INSERT INTO Odeljenje (Odeljenje_ID, Odeljenje_Naziv) VALUES ('rc', 'Referalni centar');

INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('a', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('b', 'Razmena');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('c', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('d', 'Obavezni primerak');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('e', 'Zatečeni (stari) fond');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('f', 'Sopstvena izdanja');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('k', 'Kupovina');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('o', 'Otkup');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('p', 'Poklon');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('s', 'Sopstvena izdanja');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('u', '***');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('r', '***');
INSERT INTO Nacin_nabavke (Nacin_ID, Nacin_Opis) VALUES ('sr', '***');

INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('a', 'Bibliofilski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('b', 'Broširano (tvrde korice, meke korice)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('c', 'Fascikl povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('d', 'Italijanski povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('f', 'Platno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('g', 'Poluplatno');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('h', 'Polukoža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('i', 'Spiralni povez (npr. kalendar)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('k', 'Veštačka koža');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('l', 'Ostali povezi (nove vrste, nenaved. pov, moderni)');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('m', 'Meki povez');
INSERT INTO Povez (Povez_ID, Povez_Opis) VALUES ('t', 'Tvrdi povez');

INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('1', 'Vremenski ograničena dostupnost - do 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('2', 'Vremenski ograničena dostupnost - 7 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('3', 'Vremenski ograničena dostupnost - 14 dana');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('4', 'Delimična dostupnost - čitaonica');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('5', 'Delimična dostupnost - sa dozvolom autora');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('6', 'Sadržaj dokumenta nedostupan (poseban tretman)');
INSERT INTO Dostupnost (Dostupnost_ID, Dostupnost_Opis) VALUES ('7', 'Potpuna nedostupnost (arhivski primerak ...)');

INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('I', 'Format I – Monografske publikacije I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('II', 'Format II - Monografske publikacije II format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('III', 'Format III - Monografske publikacije III format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('IV', 'Format IV - Monografske publikacije IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('RI', 'Format RI - Rariteti, monografske publikacije I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('RII', 'Format RII - Rariteti, monografske publikacije II format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('RIII', 'Format RIII - Rariteti, monografske publikacije III format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('RIV', 'Format RIV - Rariteti, monografske publikacije IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('AI', 'Format AI – Stare knjige do 1868, I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('AII', 'Format AII - Stare knjige do 1868, II format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('AIII', 'Format AIII - Stare knjige do 1868, III format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('AIV', 'Format AIV - Stare knjige do 1868, IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPI', 'Format SPI – Legat Stevana Pešića, I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPII', 'Format SPII - Legat Stevana Pešića, II format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPIII', 'Format SPIII - Legat Stevana Pešića, III format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPRI', 'Format SPRI'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPRII', 'Format SPRII'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('SPRIII', 'Format SPRIII'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('DMI', 'Format DMI');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('DMII', 'Format DMII'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('DMIII', 'Format DMIII'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('DMIV', 'Format DMIV');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('BNI', 'Format BNI – Poklon Boška Novakovića I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('BNII', 'Format BNII - Poklon Boška Novakovića II format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('BNIII', 'Format BNIII - Poklon Boška Novakovića III format'); 
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('BNIV', 'Format BNIV - Poklon Boška Novakovića IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('NI', 'Format - Note');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('NII', 'Format - Note');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('NIII', 'Format - Note');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('PlI', 'Plakat I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('PlII', 'Plakat II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('PlIII', 'Plakat III format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('PlIV', 'Plakat IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('PlV', 'Plakat lV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('FgI', 'fotografija I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('FgII', 'fotografija II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('FgIII', 'fotografija III format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('FgIV', 'fotografija IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('FgV', 'fotografija V format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('Dk', 'Pozivnice, čestitke, programi, flajeri');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('Ps', 'prospekti');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ArI', 'albumi razglednica i fotografija I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ArII', 'albumi razglednica i fotografija II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ArIII', 'albumi razglednica i fotografija III format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ArIV', 'albumi razglednica i fotografija IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('ArV', 'albumi razglednica i fotografija V format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('KalI', 'kalendari I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('KalII', 'kalendari II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('KalIII', 'kalendari III format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('KalIV', 'kalendari IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('Ra', 'razglednice');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GkI', 'kartografska građa I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GkII', 'kartografska građa II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GkIII', 'kartografska građa III format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GkIV', 'kartografska građa IV format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GkV', 'kartografska građa V format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GpI', 'gramofonske ploče I format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('GpII', 'gramofonske ploče II format');
INSERT INTO SigFormat (SigFormat_ID, Format_Opis) VALUES ('KdM', 'zvučni snimci, muzički');

INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('00','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('01','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('32','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('91','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('92','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('33','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('34','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('35','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('99','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('11','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('36','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('37','nepoznato');
INSERT INTO Invknj (invknj_id, invknj_opis) VALUES ('38','nepoznato');

INSERT INTO Counters (counter_name, counter_value) VALUES ('recordid', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('primerakid', 0); 
INSERT INTO Counters (counter_name, counter_value) VALUES ('godinaid', 0);  
INSERT INTO Counters (counter_name, counter_value) VALUES ('sveskaid', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('RN', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('00', 166058);
INSERT INTO Counters (counter_name, counter_value) VALUES ('01', 5370);
INSERT INTO Counters (counter_name, counter_value) VALUES ('02', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('03', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('04', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('05', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('06', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('07', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('08', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('09', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('10', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('11', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('12', 0);
INSERT INTO Counters (counter_name, counter_value) VALUES ('31', 3163);
INSERT INTO Counters (counter_name, counter_value) VALUES ('32', 12096);
INSERT INTO Counters (counter_name, counter_value) VALUES ('33', 1001);
INSERT INTO Counters (counter_name, counter_value) VALUES ('34', 1055);
INSERT INTO Counters (counter_name, counter_value) VALUES ('35', 2917);
INSERT INTO Counters (counter_name, counter_value) VALUES ('36', 103);
INSERT INTO Counters (counter_name, counter_value) VALUES ('37', 70);
INSERT INTO Counters (counter_name, counter_value) VALUES ('38', 8428);

INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (1,'<?xml version="1.0"?><process-type name="Monografske - kompletna obrada" pubType="1"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="010a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><initial-subfield name="7004"/><initial-subfield name="700a"/><initial-subfield name="700b"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');
INSERT INTO Tipovi_obrade (tipobr_id, tipobr_spec) VALUES (2,'<?xml version="1.0"?><process-type name="Serijske - kompletna obrada" pubType="2"><initial-subfield name="0017"/><initial-subfield name="001c"/><initial-subfield name="001d"/><initial-subfield name="011a"/><initial-subfield name="100b"/><initial-subfield name="100c"/><initial-subfield name="101a"/><initial-subfield name="102a"/><initial-subfield name="110a"/><initial-subfield name="110b"/><initial-subfield name="110c"/><initial-subfield name="200a"/><initial-subfield name="200f"/><initial-subfield name="200g"/><initial-subfield name="200h"/><initial-subfield name="200i"/><initial-subfield name="205a"/><initial-subfield name="210a"/><initial-subfield name="300a"/><mandatory-subfield name="100c"/><mandatory-subfield name="200a"/></process-type>');

INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('admin', 'admin','Bojana', 'Dimić','bdimic@uns.ns.ac.yu','napomena', 1, 1, 1, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><process-type name="Serijske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');
INSERT INTO Bibliotekari (username, password, ime, prezime, email, napomena, obrada, cirkulacija, administracija, context) VALUES ('circ', 'circ','Danijela','Tesendic','tesendic@uns.ns.ac.yu','', 0, 1, 0, '<?xml version="1.0"?><librarian-context><process-type name="Monografske - kompletna obrada"/><default-process-type name="Monografske - kompletna obrada"/><prefixes pref1="AU" pref2="TI" pref3="PU" pref4="PY" pref5="KW"/></librarian-context>');



